
#include "CppUTest/TestHarness.h"
#include "CppUTest/TestHarness_c.h"

IMPORT_TEST_GROUP(Crc32TestsGroup);

IMPORT_TEST_GROUP(HotReloadTestsGroup);

IMPORT_TEST_GROUP(GpioTestsGroup);

IMPORT_TEST_GROUP(RedundantStorageTestsGroup);

IMPORT_TEST_GROUP(SettingsTestsGroup);

IMPORT_TEST_GROUP(RestartCounterTestsGroup);

IMPORT_TEST_GROUP(ButtonTestsGroup);
IMPORT_TEST_GROUP(DisplayTestsGroup);
IMPORT_TEST_GROUP(LogicInputNOTestsGroup);
IMPORT_TEST_GROUP(LogicInputNCTestsGroup);
IMPORT_TEST_GROUP(LogicCommonInputTestsGroup);
IMPORT_TEST_GROUP(LogicCommonComparatorTestsGroup);
IMPORT_TEST_GROUP(LogicTimerSecsTestsGroup);
IMPORT_TEST_GROUP(LogicTimerMSecsTestsGroup);
IMPORT_TEST_GROUP(LogicCommonTimerTestsGroup);
IMPORT_TEST_GROUP(LogicNetworkTestsGroup);
IMPORT_TEST_GROUP(LogicComparatorLsTestsGroup);
IMPORT_TEST_GROUP(LogicComparatorLETestsGroup);
IMPORT_TEST_GROUP(LogicComparatorGrTestsGroup);
IMPORT_TEST_GROUP(LogicComparatorGETestsGroup);

IMPORT_TEST_GROUP(StatusBarTestsGroup);

IMPORT_TEST_GROUP(LogicDecOutputTestsGroup);
IMPORT_TEST_GROUP(LogicDirectOutputTestsGroup);
IMPORT_TEST_GROUP(LogicSetOutputTestsGroup);
IMPORT_TEST_GROUP(LogicResetOutputTestsGroup);
IMPORT_TEST_GROUP(LogicIncOutputTestsGroup);

IMPORT_TEST_GROUP(LogicControllerTestsGroup);
IMPORT_TEST_GROUP(ScrollBarTestsGroup);

IMPORT_TEST_GROUP(LogicLadderTestsGroup);
IMPORT_TEST_GROUP(LogicLadderDesignerTestsGroup);

IMPORT_TEST_GROUP(TvElementTypeTestsGroup);

IMPORT_TEST_GROUP(LogicElementsBoxTestsGroup);

IMPORT_TEST_GROUP(LogicCommonOutputTestsGroup);
IMPORT_TEST_GROUP(ProcessWakeupServiceTestsGroup);
IMPORT_TEST_GROUP(LogicIndicatorTestsGroup);
IMPORT_TEST_GROUP(LogicControllerVariableTestsGroup);
IMPORT_TEST_GROUP(LogicControllerDOTestsGroup);
IMPORT_TEST_GROUP(LogicControllerDITestsGroup);

IMPORT_TEST_GROUP(LogicWiFiServiceTestsGroup);
IMPORT_TEST_GROUP(LogicWiFiRequestsTestsGroup);

IMPORT_TEST_GROUP(ServiceModeHandlerTestsGroup);

IMPORT_TEST_GROUP(BackupsStorageTestsGroup);

IMPORT_TEST_GROUP(LogicWiFiBindingTestsGroup);
IMPORT_TEST_GROUP(LogicWiFiApBindingTestsGroup);
IMPORT_TEST_GROUP(LogicWiFiStaBindingTestsGroup);