
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>

#include "main/redundant_storage.cpp"
#include "main/storage.cpp"

#include "main/Display/EditableElement.cpp"
#include "main/Display/LabeledLogicItem.cpp"
#include "main/Display/MapIOIndicator.cpp"
#include "main/Display/display.cpp"
#include "main/LogicProgram/Controller.cpp"
#include "main/LogicProgram/InputElement.cpp"
#include "main/LogicProgram/InputOutputElement.cpp"
#include "main/LogicProgram/Inputs/CommonComparator.cpp"
#include "main/LogicProgram/Inputs/CommonInput.cpp"
#include "main/LogicProgram/Inputs/CommonTimer.cpp"
#include "main/LogicProgram/Inputs/InputNC.cpp"
#include "main/LogicProgram/Inputs/WiFiInput.cpp"
#include "main/LogicProgram/Ladder.cpp"
#include "main/LogicProgram/LadderDesigner.cpp"
#include "main/LogicProgram/LadderInitial.cpp"
#include "main/LogicProgram/LadderStoring.cpp"
#include "main/LogicProgram/LogicElement.cpp"
#include "main/LogicProgram/MapIO.cpp"
#include "main/LogicProgram/Network.cpp"
#include "main/LogicProgram/Outputs/CommonOutput.cpp"
#include "main/LogicProgram/Outputs/DecOutput.cpp"
#include "main/LogicProgram/Outputs/DirectOutput.cpp"
#include "main/LogicProgram/Outputs/IncOutput.cpp"
#include "main/LogicProgram/Outputs/ResetOutput.cpp"
#include "main/LogicProgram/Outputs/SetOutput.cpp"
#include "main/LogicProgram/Serializer/Record.cpp"
#include "main/LogicProgram/Wire.cpp"
#include "main/buttons.cpp"
